# Form implementation generated from reading ui file 'ui\form.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.in_btn = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_btn.sizePolicy().hasHeightForWidth())
        self.in_btn.setSizePolicy(sizePolicy)
        self.in_btn.setObjectName("in_btn")
        self.gridLayout.addWidget(self.in_btn, 0, 0, 1, 1)
        self.in_lbl = QtWidgets.QLabel(parent=Form)
        self.in_lbl.setObjectName("in_lbl")
        self.gridLayout.addWidget(self.in_lbl, 0, 1, 1, 1)
        self.run_btn = QtWidgets.QPushButton(parent=Form)
        self.run_btn.setObjectName("run_btn")
        self.gridLayout.addWidget(self.run_btn, 1, 0, 1, 2)
        self.log_txt = QtWidgets.QPlainTextEdit(parent=Form)
        self.log_txt.setObjectName("log_txt")
        self.gridLayout.addWidget(self.log_txt, 2, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.in_btn.setText(_translate("Form", "Choose ZipFile"))
        self.in_lbl.setText(_translate("Form", "---"))
        self.run_btn.setText(_translate("Form", "Run"))
